services:
  backend:
    build: 
      context: ./backend
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=sauna_user
      - DB_PASSWORD=sauna_password
      - DB_NAME=sauna_db
    ports:
      - "8080:8080"
    networks:
      - sauna-network

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
      - CI=true
      - NODE_ENV=test
    depends_on:
      - backend
    networks:
      - sauna-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sauna_db
      MYSQL_USER: sauna_user
      MYSQL_PASSWORD: sauna_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sauna-network

networks:
  sauna-network:

volumes:
  mysql-data:
